//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCampaign.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualCampaign.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _lock {
            get {
                object obj = ResourceManager.GetObject("_lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abilityDefault {
            get {
                object obj = ResourceManager.GetObject("abilityDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armband
        ///Belt
        ///Cape
        ///Circlet
        ///Cloak
        ///Earring
        ///Gloves
        ///Helmet
        ///Leggings
        ///Necklace
        ///Pauldron
        ///Ring
        ///Shoes.
        /// </summary>
        internal static string accessory_types {
            get {
                return ResourceManager.GetString("accessory_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-1
        ///-5:-8
        ///-4:-7
        ///-3:-6
        ///-2:-5
        ///-1:-4
        ///0:-3
        ///1:-2
        ///2:-2
        ///3:-1
        ///4:-1
        ///5:-1
        ///6:0
        ///7:0
        ///8:0
        ///9:0
        ///10:0
        ///11:1
        ///12:1
        ///13:2
        ///14:2
        ///15:3
        ///16:3
        ///17:4
        ///18:4
        ///19:5
        ///20:6
        ///21:7
        ///22:8
        ///23:9
        ///24:10
        ///25:12
        ///26:14
        ///27:16
        ///28:28
        ///29:20
        ///30:22
        ///P:2.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrow
        ///Bolt
        ///Bullet
        ///Dart.
        /// </summary>
        internal static string ammo_types {
            get {
                return ResourceManager.GetString("ammo_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light
        ///Medium
        ///Heavy
        ///Shield.
        /// </summary>
        internal static string armor_types {
            get {
                return ResourceManager.GetString("armor_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to border: 1px solid black;
        ///.
        /// </summary>
        internal static string article_browser {
            get {
                return ResourceManager.GetString("article_browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to small_marker_blue
        ///marker_black
        ///marker_black_pointed
        ///marker_black_round
        ///marker_blue
        ///marker_blue_pointed
        ///marker_blue_round
        ///marker_brown
        ///marker_brown_pointed
        ///marker_brown_round
        ///marker_green
        ///marker_green_pointed
        ///marker_green_round
        ///marker_orange
        ///marker_orange_pointed
        ///marker_orange_round
        ///marker_purple
        ///marker_purpe_pointed
        ///marker_purple_round
        ///marker_red
        ///marker_red_pointed
        ///marker_red_round
        ///marker_teal
        ///marker_teal_pointed
        ///marker_teal_round
        ///marker_white
        ///marker_white_pointed
        ///marker_white_rou [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string atlas_bg_options {
            get {
                return ResourceManager.GetString("atlas_bg_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city_mark
        ///fort_mark
        ///history_mark
        ///landmark_mark
        ///map_mark
        ///ruin_mark
        ///speech_mark
        ///town_mark.
        /// </summary>
        internal static string atlas_icon_options {
            get {
                return ResourceManager.GetString("atlas_icon_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:0
        ///2:0
        ///3:0
        ///4:0
        ///5:0
        ///6:0
        ///7:0
        ///8:0
        ///9:0
        ///10:1
        ///11:1
        ///12:1
        ///13:2
        ///14:2
        ///15:3
        ///16:4
        ///17:5
        ///18:6
        ///19:8
        ///20:10
        ///21:12
        ///22:13
        ///23:16
        ///24:18
        ///25:20
        ///26:23
        ///27:26
        ///28:29
        ///29:32
        ///30:35
        ///P:3.
        /// </summary>
        internal static string Awareness {
            get {
                return ResourceManager.GetString("Awareness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:1
        ///-4:1
        ///-3:1
        ///-2:1
        ///-1:1
        ///0:1
        ///1:1
        ///2:1
        ///3:1
        ///4:1
        ///5:1
        ///6:1
        ///7:1
        ///8:1
        ///9:1
        ///10:2
        ///11:2
        ///12:2
        ///13:3
        ///14:3
        ///15:3
        ///16:4
        ///17:4
        ///18:5
        ///19:5
        ///20:6
        ///21:6
        ///22:7
        ///23:7
        ///24:8
        ///25:9
        ///26:10
        ///27:11
        ///28:12
        ///29:13
        ///30:15
        ///P:2.
        /// </summary>
        internal static string Base_Damage {
            get {
                return ResourceManager.GetString("Base_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:1
        ///2:1
        ///3:1
        ///4:2
        ///5:2
        ///6:3
        ///7:3
        ///8:4
        ///9:4
        ///10:5
        ///11:6
        ///12:7
        ///13:8
        ///14:9
        ///15:10
        ///16:11
        ///17:13
        ///18:15
        ///19:17
        ///20:20
        ///21:23
        ///22:26
        ///23:30
        ///24:35
        ///25:40
        ///26:46
        ///27:53
        ///28:61
        ///29:70
        ///30:80
        ///P:12.
        /// </summary>
        internal static string Base_Defense {
            get {
                return ResourceManager.GetString("Base_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:1
        ///2:1
        ///3:1
        ///4:1
        ///5:1
        ///6:1
        ///7:1
        ///8:1
        ///9:1
        ///10:2
        ///11:2
        ///12:2
        ///13:3
        ///14:3
        ///15:3
        ///16:4
        ///17:4
        ///18:5
        ///19:5
        ///20:6
        ///21:6
        ///22:7
        ///23:7
        ///24:8
        ///25:9
        ///26:10
        ///27:11
        ///28:12
        ///29:13
        ///30:15
        ///P:2.
        /// </summary>
        internal static string Base_Magic_Damage {
            get {
                return ResourceManager.GetString("Base_Magic_Damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:1
        ///2:1
        ///3:1
        ///4:2
        ///5:2
        ///6:3
        ///7:3
        ///8:4
        ///9:4
        ///10:5
        ///11:6
        ///12:7
        ///13:8
        ///14:9
        ///15:10
        ///16:11
        ///17:13
        ///18:15
        ///19:17
        ///20:20
        ///21:23
        ///22:26
        ///23:30
        ///24:35
        ///25:40
        ///26:46
        ///27:53
        ///28:61
        ///29:70
        ///30:80
        ///P:12.
        /// </summary>
        internal static string Base_Magic_Defense {
            get {
                return ResourceManager.GetString("Base_Magic_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blueBlip {
            get {
                object obj = ResourceManager.GetObject("blueBlip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:1
        ///1:2
        ///2:2
        ///3:3
        ///4:3
        ///5:3
        ///6:4
        ///7:4
        ///8:4
        ///9:4
        ///10:5
        ///11:6
        ///12:7
        ///13:9
        ///14:11
        ///15:13
        ///16:15
        ///17:17
        ///18:19
        ///19:22
        ///20:25
        ///21:28
        ///22:31
        ///23:34
        ///24:37
        ///25:40
        ///26:44
        ///27:48
        ///28:53
        ///29:58
        ///30:63
        ///P:5.
        /// </summary>
        internal static string Channeling {
            get {
                return ResourceManager.GetString("Channeling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap city_mark {
            get {
                object obj = ResourceManager.GetObject("city_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T:STRHPB
        ///N:-2
        ///P:42
        ///-20:-40
        ///-19:-38
        ///-18:-36
        ///-17:-34
        ///-16:-32
        ///-15:-30
        ///-14:-28
        ///-13:-26
        ///-12:-24
        ///-11:-22
        ///-10:-20
        ///-9:-18
        ///-8:-16
        ///-7:-14
        ///-6:-12
        ///-5:-10
        ///-4:-8
        ///-3:-6
        ///-2:-4
        ///-1:-2
        ///0:0
        ///1:2
        ///2:4
        ///3:6
        ///4:8
        ///5:10
        ///6:12
        ///7:14
        ///8:16
        ///9:18
        ///10:20
        ///11:22
        ///12:24
        ///13:26
        ///14:28
        ///15:30
        ///16:32
        ///17:34
        ///18:36
        ///19:38
        ///20:40
        ///21:42
        ///22:44
        ///23:46
        ///24:48
        ///25:50
        ///26:54
        ///27:58
        ///28:62
        ///29:66
        ///30:70
        ///31:74
        ///32:78
        ///33:82
        ///34:86
        ///35:90
        ///36:94
        ///37:98
        ///38:102
        ///39:106
        ///40:110
        ///41:114
        ///42:118
        ///43:122
        ///44:126
        ///45:130
        ///46:134
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassicAttributes {
            get {
                return ResourceManager.GetString("ClassicAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap closeIcon {
            get {
                object obj = ResourceManager.GetObject("closeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a
        ///abandon
        ///ability
        ///able
        ///abortion
        ///about
        ///above
        ///abroad
        ///absence
        ///absolute
        ///absolutely
        ///absorb
        ///abuse
        ///academic
        ///accept
        ///access
        ///accident
        ///accompany
        ///accomplish
        ///according
        ///account
        ///accurate
        ///accuse
        ///achieve
        ///achievement
        ///acid
        ///acknowledge
        ///acquire
        ///across
        ///act
        ///action
        ///active
        ///activist
        ///activity
        ///actor
        ///actress
        ///actual
        ///actually
        ///ad
        ///adapt
        ///add
        ///addition
        ///additional
        ///address
        ///adequate
        ///adjust
        ///adjustment
        ///administration
        ///administrator
        ///admire
        ///admission
        ///admit
        ///adolescent
        ///adopt
        ///adult
        ///advance
        ///advanced [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Common_Words {
            get {
                return ResourceManager.GetString("Common_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material
        ///Wood
        ///Metal
        ///Gem.
        /// </summary>
        internal static string component_types {
            get {
                return ResourceManager.GetString("component_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food
        ///Potion.
        /// </summary>
        internal static string consumable_types {
            get {
                return ResourceManager.GetString("consumable_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crosshairs {
            get {
                object obj = ResourceManager.GetObject("crosshairs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:1
        ///-3:2
        ///-2:3
        ///-1:4
        ///0:5
        ///1:6
        ///2:6
        ///3:7
        ///4:7
        ///5:8
        ///6:8
        ///7:9
        ///8:9
        ///9:10
        ///10:10
        ///11:11
        ///12:11
        ///13:12
        ///14:12
        ///15:13
        ///16:13
        ///17:14
        ///18:14
        ///19:15
        ///20:16
        ///21:17
        ///22:18
        ///23:19
        ///24:20
        ///25:22
        ///26:24
        ///27:26
        ///28:28
        ///29:30
        ///30:32
        ///P:2.
        /// </summary>
        internal static string Dodge {
            get {
                return ResourceManager.GetString("Dodge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap elemental_icon {
            get {
                object obj = ResourceManager.GetObject("elemental_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abigail
        ///Ada
        ///Adela
        ///Ailith
        ///Alainna
        ///Alainne
        ///Albreda
        ///Alessia
        ///Alexandria
        ///Alice
        ///Allison
        ///Alvina
        ///Amanda
        ///Amara
        ///Amiria
        ///Ariana
        ///Ashe
        ///Ashley
        ///Ava
        ///Aveline
        ///Audrey
        ///Bailey
        ///Basilia
        ///Beatrice
        ///Belinda
        ///Bethany
        ///Blair
        ///Bridget
        ///Brooke
        ///Camila
        ///Carmen
        ///Caroline
        ///Catalina
        ///Cecilia
        ///Cecily
        ///Charlotte
        ///Claire
        ///Clarice
        ///Clarissa
        ///Claudia
        ///Colleen
        ///Constance
        ///Cora
        ///Cynthia
        ///Dae
        ///Danica
        ///Danielle
        ///Danni
        ///Daphne
        ///Darva
        ///Dawn
        ///Deidra
        ///Diana
        ///Dylena
        ///Edith
        ///Ediva
        ///Elaine
        ///Elena
        ///Eleanor
        ///Eliana
        ///Elizabeth
        ///Eloise
        ///E [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string First_Names_F {
            get {
                return ResourceManager.GetString("First_Names_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adam
        ///Ademar
        ///Adrian
        ///Aidan
        ///Alan
        ///Alard
        ///Alavon
        ///Albert
        ///Aldous
        ///Alexander
        ///Alfred
        ///Allastor
        ///Alphonse
        ///Allucard
        ///Amoran
        ///Ancel
        ///Anders
        ///Ansem
        ///Anthony
        ///Archibald
        ///Arnold
        ///Arthur
        ///Arundel
        ///Ashton
        ///Barden
        ///Bardolph
        ///Barry
        ///Bartholomew
        ///Belton
        ///Benjamin
        ///Bennett
        ///Bernard
        ///Bertram
        ///Blake
        ///Booker
        ///Boris
        ///Bowman
        ///Bradley
        ///Brandon
        ///Brayden
        ///Brian
        ///Bruce
        ///Bryce
        ///Burke
        ///Cabell
        ///Caden
        ///Cadmon
        ///Caleb
        ///Calvin
        ///Carlton
        ///Carlyle
        ///Carson
        ///Cassius
        ///Cedric
        ///Clark
        ///Clive
        ///Charles
        ///Christopher
        ///Colin
        ///Colton
        ///Conan
        ///Conrad        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string First_Names_M {
            get {
                return ResourceManager.GetString("First_Names_M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fort_mark {
            get {
                object obj = ResourceManager.GetObject("fort_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        internal static string generic_types {
            get {
                return ResourceManager.GetString("generic_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap green_check {
            get {
                object obj = ResourceManager.GetObject("green_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greenBlip {
            get {
                object obj = ResourceManager.GetObject("greenBlip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap greyBlip {
            get {
                object obj = ResourceManager.GetObject("greyBlip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-0.5
        ///00:5
        ///01:5
        ///02:6
        ///03:6
        ///04:7
        ///05:7
        ///06:8
        ///07:8
        ///08:9
        ///09:9
        ///10:10
        ///11:10
        ///12:11
        ///13:11
        ///14:12
        ///15:12
        ///16:13
        ///17:13
        ///18:14
        ///19:14
        ///20:15
        ///21:15
        ///22:16
        ///23:16
        ///24:17
        ///25:17
        ///26:18
        ///27:18
        ///28:19
        ///29:19
        ///30:20
        ///31:20
        ///32:21
        ///33:21
        ///34:22
        ///35:22
        ///36:23
        ///37:23
        ///38:24
        ///39:24
        ///40:25
        ///41:25
        ///42:26
        ///43:26
        ///44:27
        ///45:27
        ///46:28
        ///47:28
        ///48:29
        ///49:29
        ///50:30
        ///P:0.5.
        /// </summary>
        internal static string High_EPMP {
            get {
                return ResourceManager.GetString("High_EPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-1
        ///00:21
        ///01:22
        ///02:23
        ///03:24
        ///04:25
        ///05:26
        ///06:27
        ///07:28
        ///08:29
        ///09:30
        ///10:31
        ///11:33
        ///12:34
        ///13:36
        ///14:37
        ///15:39
        ///16:40
        ///17:42
        ///18:44
        ///19:45
        ///20:47
        ///21:49
        ///22:51
        ///23:53
        ///24:55
        ///25:57
        ///26:59
        ///27:61
        ///28:64
        ///29:66
        ///30:68
        ///31:70
        ///32:73
        ///33:76
        ///34:78
        ///35:81
        ///36:84
        ///37:86
        ///38:89
        ///39:91
        ///40:94
        ///41:97
        ///42:100
        ///43:103
        ///44:107
        ///45:110
        ///46:113
        ///47:116
        ///48:119
        ///49:122
        ///50:126
        ///P:5.
        /// </summary>
        internal static string High_HP {
            get {
                return ResourceManager.GetString("High_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-0.5
        ///00:10
        ///01:10
        ///02:11
        ///03:11
        ///04:12
        ///05:12
        ///06:13
        ///07:13
        ///08:14
        ///09:14
        ///10:15
        ///11:15
        ///12:16
        ///13:16
        ///14:17
        ///15:17
        ///16:18
        ///17:18
        ///18:19
        ///19:19
        ///20:20
        ///21:20
        ///22:21
        ///23:21
        ///24:22
        ///25:22
        ///26:23
        ///27:23
        ///28:24
        ///29:24
        ///30:25
        ///31:25
        ///32:26
        ///33:26
        ///34:27
        ///35:27
        ///36:28
        ///37:28
        ///38:29
        ///39:29
        ///40:30
        ///41:30
        ///42:31
        ///43:31
        ///44:32
        ///45:32
        ///46:33
        ///47:33
        ///48:34
        ///49:34
        ///50:35
        ///P:0.5.
        /// </summary>
        internal static string Highest_EPMP {
            get {
                return ResourceManager.GetString("Highest_EPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-1
        ///00:22
        ///01:23
        ///02:24
        ///03:25
        ///04:26
        ///05:27
        ///06:28
        ///07:29
        ///08:30
        ///09:31
        ///10:33
        ///11:34
        ///12:36
        ///13:37
        ///14:39
        ///15:41
        ///16:42
        ///17:44
        ///18:46
        ///19:47
        ///20:49
        ///21:51
        ///22:53
        ///23:56
        ///24:58
        ///25:60
        ///26:62
        ///27:64
        ///28:67
        ///29:69
        ///30:71
        ///31:74
        ///32:77
        ///33:79
        ///34:82
        ///35:85
        ///36:88
        ///37:90
        ///38:93
        ///39:94
        ///40:99
        ///41:102
        ///42:105
        ///43:108
        ///44:112
        ///45:115
        ///46:118
        ///47:122
        ///48:125
        ///49:128
        ///50:132
        ///P:5.
        /// </summary>
        internal static string Highest_HP {
            get {
                return ResourceManager.GetString("Highest_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap history_mark {
            get {
                object obj = ResourceManager.GetObject("history_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_delete_active {
            get {
                object obj = ResourceManager.GetObject("item_delete_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_delete_active_highlight {
            get {
                object obj = ResourceManager.GetObject("item_delete_active_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_delete_inactive {
            get {
                object obj = ResourceManager.GetObject("item_delete_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_equip_active {
            get {
                object obj = ResourceManager.GetObject("item_equip_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_equip_active_highlight {
            get {
                object obj = ResourceManager.GetObject("item_equip_active_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_equip_inactive {
            get {
                object obj = ResourceManager.GetObject("item_equip_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_equip_inactive_highlight {
            get {
                object obj = ResourceManager.GetObject("item_equip_inactive_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_star_active {
            get {
                object obj = ResourceManager.GetObject("item_star_active", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_star_active_highlight {
            get {
                object obj = ResourceManager.GetObject("item_star_active_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_star_inactive {
            get {
                object obj = ResourceManager.GetObject("item_star_inactive", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap item_star_inactive_highlight {
            get {
                object obj = ResourceManager.GetObject("item_star_inactive_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keyhole {
            get {
                object obj = ResourceManager.GetObject("keyhole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap landmark_mark {
            get {
                object obj = ResourceManager.GetObject("landmark_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achard
        ///Addinell
        ///Aguilon
        ///Albelin
        ///Altard
        ///Anderson
        ///Andreci
        ///Arnold
        ///Ashe
        ///Aubert
        ///Azor
        ///Bainard
        ///Ballard
        ///Basset
        ///Baudry
        ///Bavent
        ///Beauvallet
        ///Bele
        ///Bellecote
        ///Blancbaston
        ///Bolam
        ///Bolbec
        ///Bourdet
        ///Bradwardine
        ///Buron
        ///Carnet
        ///Cavelier
        ///Chauncy
        ///Civille
        ///Claville
        ///Corbet
        ///Corbon
        ///Courci
        ///Culai
        ///Dalyngridge
        ///Danvers
        ///Day
        ///Deane
        ///Dedrick
        ///Delaney
        ///Desmarres
        ///Douval
        ///Draper
        ///Dunn
        ///Durville
        ///Dyson
        ///Eldridge
        ///Elliot
        ///Ellis
        ///Elmond
        ///Elwes
        ///Emory
        ///Eregost
        ///Evermire
        ///Fairchild
        ///Fairfax
        ///Fergant
        ///Fisher
        ///Fitzroy
        ///Fl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Last_Names {
            get {
                return ResourceManager.GetString("Last_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-0.5
        ///00:-5
        ///01:-5
        ///02:-4
        ///03:-4
        ///04:-3
        ///05:-3
        ///06:-2
        ///07:-2
        ///08:-1
        ///09:-1
        ///10:0
        ///11:0
        ///12:1
        ///13:1
        ///14:2
        ///15:2
        ///16:3
        ///17:3
        ///18:4
        ///19:4
        ///20:5
        ///21:5
        ///22:6
        ///23:6
        ///24:7
        ///25:7
        ///26:8
        ///27:8
        ///28:9
        ///29:9
        ///30:10
        ///31:10
        ///32:11
        ///33:11
        ///34:12
        ///35:12
        ///36:13
        ///37:13
        ///38:14
        ///39:14
        ///40:15
        ///41:15
        ///42:16
        ///43:16
        ///44:17
        ///45:17
        ///46:18
        ///47:18
        ///48:19
        ///49:19
        ///50:20
        ///P:0.5.
        /// </summary>
        internal static string Low_EPMP {
            get {
                return ResourceManager.GetString("Low_EPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-1
        ///00:19
        ///01:19
        ///02:20
        ///03:21
        ///04:22
        ///05:23
        ///06:24
        ///07:25
        ///08:26
        ///09:27
        ///10:28
        ///11:29
        ///12:31
        ///13:32
        ///14:34
        ///15:35
        ///16:37
        ///17:38
        ///18:39
        ///19:41
        ///20:42
        ///21:44
        ///22:46
        ///23:48
        ///24:50
        ///25:52
        ///26:54
        ///27:56
        ///28:57
        ///29:59
        ///30:61
        ///31:64
        ///32:66
        ///33:68
        ///34:71
        ///35:73
        ///36:76
        ///37:78
        ///38:80
        ///39:83
        ///40:85
        ///41:88
        ///42:91
        ///43:94
        ///44:96
        ///45:99
        ///46:102
        ///47:105
        ///48:108
        ///49:111
        ///50:114
        ///P:5.
        /// </summary>
        internal static string Low_HP {
            get {
                return ResourceManager.GetString("Low_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-0.5
        ///00:-10
        ///01:-10
        ///02:-9
        ///03:-9
        ///04:-8
        ///05:-8
        ///06:-7
        ///07:-7
        ///08:-6
        ///09:-6
        ///10:-5
        ///11:-5
        ///12:-4
        ///13:-4
        ///14:-3
        ///15:-3
        ///16:-2
        ///17:-2
        ///18:-1
        ///19:-1
        ///20:0
        ///21:0
        ///22:1
        ///23:1
        ///24:2
        ///25:2
        ///26:3
        ///27:3
        ///28:4
        ///29:4
        ///30:5
        ///31:5
        ///32:6
        ///33:6
        ///34:7
        ///35:7
        ///36:8
        ///37:8
        ///38:9
        ///39:9
        ///40:10
        ///41:10
        ///42:11
        ///43:11
        ///44:12
        ///45:12
        ///46:13
        ///47:13
        ///48:14
        ///49:14
        ///50:15
        ///P:0.5.
        /// </summary>
        internal static string Lowest_EPMP {
            get {
                return ResourceManager.GetString("Lowest_EPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-1
        ///00:18
        ///01:18
        ///02:19
        ///03:20
        ///04:21
        ///05:22
        ///06:23
        ///07:24
        ///08:25
        ///09:26
        ///10:27
        ///11:28
        ///12:29
        ///13:30
        ///14:32
        ///15:33
        ///16:34
        ///17:36
        ///18:37
        ///19:38
        ///20:40
        ///21:41
        ///22:43
        ///23:45
        ///24:47
        ///25:49
        ///26:51
        ///27:52
        ///28:54
        ///29:56
        ///30:58
        ///31:60
        ///32:63
        ///33:65
        ///34:67
        ///35:69
        ///36:72
        ///37:74
        ///38:76
        ///39:78
        ///40:81
        ///41:83
        ///42:86
        ///43:89
        ///44:91
        ///45:94
        ///46:97
        ///47:99
        ///48:102
        ///49:105
        ///50:108
        ///P:5.
        /// </summary>
        internal static string Lowest_HP {
            get {
                return ResourceManager.GetString("Lowest_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:1
        ///2:1
        ///3:1
        ///4:2
        ///5:2
        ///6:3
        ///7:3
        ///8:4
        ///9:4
        ///10:5
        ///11:6
        ///12:7
        ///13:8
        ///14:9
        ///15:10
        ///16:11
        ///17:13
        ///18:15
        ///19:17
        ///20:20
        ///21:23
        ///22:26
        ///23:30
        ///24:35
        ///25:40
        ///26:46
        ///27:53
        ///28:61
        ///29:70
        ///30:80
        ///P:12.
        /// </summary>
        internal static string MagicPower {
            get {
                return ResourceManager.GetString("MagicPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_mark {
            get {
                object obj = ResourceManager.GetObject("map_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_black {
            get {
                object obj = ResourceManager.GetObject("marker_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_black_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_black_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_black_round {
            get {
                object obj = ResourceManager.GetObject("marker_black_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_blue {
            get {
                object obj = ResourceManager.GetObject("marker_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_blue_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_blue_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_blue_round {
            get {
                object obj = ResourceManager.GetObject("marker_blue_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_brown {
            get {
                object obj = ResourceManager.GetObject("marker_brown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_brown_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_brown_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_brown_round {
            get {
                object obj = ResourceManager.GetObject("marker_brown_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_cave {
            get {
                object obj = ResourceManager.GetObject("marker_cave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_desert {
            get {
                object obj = ResourceManager.GetObject("marker_desert", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_forest {
            get {
                object obj = ResourceManager.GetObject("marker_forest", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_green {
            get {
                object obj = ResourceManager.GetObject("marker_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_green_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_green_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_green_round {
            get {
                object obj = ResourceManager.GetObject("marker_green_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_island {
            get {
                object obj = ResourceManager.GetObject("marker_island", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_lake {
            get {
                object obj = ResourceManager.GetObject("marker_lake", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_mountain {
            get {
                object obj = ResourceManager.GetObject("marker_mountain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_orange {
            get {
                object obj = ResourceManager.GetObject("marker_orange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_orange_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_orange_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_orange_round {
            get {
                object obj = ResourceManager.GetObject("marker_orange_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_purple {
            get {
                object obj = ResourceManager.GetObject("marker_purple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_purple_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_purple_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_purple_round {
            get {
                object obj = ResourceManager.GetObject("marker_purple_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_red {
            get {
                object obj = ResourceManager.GetObject("marker_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_red_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_red_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_red_round {
            get {
                object obj = ResourceManager.GetObject("marker_red_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_river {
            get {
                object obj = ResourceManager.GetObject("marker_river", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_route {
            get {
                object obj = ResourceManager.GetObject("marker_route", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_teal {
            get {
                object obj = ResourceManager.GetObject("marker_teal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_teal_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_teal_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_teal_round {
            get {
                object obj = ResourceManager.GetObject("marker_teal_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_valley {
            get {
                object obj = ResourceManager.GetObject("marker_valley", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_white {
            get {
                object obj = ResourceManager.GetObject("marker_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_white_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_white_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_white_round {
            get {
                object obj = ResourceManager.GetObject("marker_white_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_yellow {
            get {
                object obj = ResourceManager.GetObject("marker_yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_yellow_pointed {
            get {
                object obj = ResourceManager.GetObject("marker_yellow_pointed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap marker_yellow_round {
            get {
                object obj = ResourceManager.GetObject("marker_yellow_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ish|  a:s | he|1310
        ///i h| aa:s | he|1
        ///i h| ae:s |she|2
        ///is | ae:s | he|2
        ///ish| ah:s |s e|4
        ///i h| ai:s | he|69
        ///i h| ao:s |s e|2
        ///ish|aqu:s |s  |1
        ///ish| ar:s |she|182
        ///i h| au:s |she|17
        ///is | au:s | he|17
        ///i h| ay:s |she|33
        ///is | ay:s | he|33
        ///
        ///is |  b:h |s e|271
        /// s | bb:h |s  |1
        /// s | bc:h |s  |1
        /// s | bd:h |s  |1
        /// s | bf:h |s  |1
        /// s | bg:h |s  |1
        /// s | bh:h |s  |1
        /// s | bj:h |s  |4
        /// s | bk:h |s  |1
        /// s | bl:h |s  |49
        /// s | bm:h |s  |2
        /// s | bn:h |s  |1
        /// s | bp:h |s  |1
        /// s |bqu:h |s  |1
        ///is | br:h | [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phonetics {
            get {
                return ResourceManager.GetString("Phonetics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:1
        ///2:1
        ///3:1
        ///4:2
        ///5:2
        ///6:3
        ///7:3
        ///8:4
        ///9:4
        ///10:5
        ///11:6
        ///12:7
        ///13:8
        ///14:9
        ///15:10
        ///16:11
        ///17:13
        ///18:15
        ///19:17
        ///20:20
        ///21:23
        ///22:26
        ///23:30
        ///24:35
        ///25:40
        ///26:46
        ///27:53
        ///28:61
        ///29:70
        ///30:80
        ///P:12.
        /// </summary>
        internal static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redBlip {
            get {
                object obj = ResourceManager.GetObject("redBlip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:1
        ///2:1
        ///3:1
        ///4:1
        ///5:1
        ///6:2
        ///7:2
        ///8:2
        ///9:2
        ///10:2
        ///11:2
        ///12:3
        ///13:3
        ///14:4
        ///15:5
        ///16:6
        ///17:7
        ///18:8
        ///19:9
        ///20:10
        ///21:11
        ///22:12
        ///23:13
        ///24:14
        ///25:15
        ///26:17
        ///27:19
        ///28:21
        ///29:23
        ///30:25
        ///P:3.
        /// </summary>
        internal static string Regen {
            get {
                return ResourceManager.GetString("Regen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap roll_button_icon {
            get {
                object obj = ResourceManager.GetObject("roll_button_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rollIcon {
            get {
                object obj = ResourceManager.GetObject("rollIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ruin_mark {
            get {
                object obj = ResourceManager.GetObject("ruin_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small_marker_blue {
            get {
                object obj = ResourceManager.GetObject("small_marker_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speech_mark {
            get {
                object obj = ResourceManager.GetObject("speech_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:1
        ///-3:1
        ///-2:2
        ///-1:2
        ///0:3
        ///1:3
        ///2:3
        ///3:3
        ///4:4
        ///5:4
        ///6:5
        ///7:5
        ///8:6
        ///9:6
        ///10:7
        ///11:7
        ///12:8
        ///13:8
        ///14:9
        ///15:10
        ///16:11
        ///17:12
        ///18:13
        ///19:14
        ///20:15
        ///21:16
        ///22:17
        ///23:18
        ///24:19
        ///25:20
        ///26:22
        ///27:24
        ///28:26
        ///29:28
        ///30:30
        ///P:3.
        /// </summary>
        internal static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-0.5
        ///-5:3
        ///-4:4
        ///-3:4
        ///-2:5
        ///-1:5
        ///0:6
        ///1:6
        ///2:7
        ///3:7
        ///4:8
        ///5:8
        ///6:9
        ///7:10
        ///8:11
        ///9:13
        ///10:15
        ///11:16
        ///12:17
        ///13:18
        ///14:19
        ///15:20
        ///16:21
        ///17:22
        ///18:23
        ///19:24
        ///20:25
        ///21:27
        ///22:29
        ///23:31
        ///24:33
        ///25:35
        ///26:38
        ///27:41
        ///28:44
        ///29:47
        ///30:50
        ///P:4.
        /// </summary>
        internal static string Spirit {
            get {
                return ResourceManager.GetString("Spirit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:1
        ///1:2
        ///2:2
        ///3:3
        ///4:3
        ///5:3
        ///6:4
        ///7:4
        ///8:4
        ///9:4
        ///10:5
        ///11:6
        ///12:7
        ///13:9
        ///14:11
        ///15:13
        ///16:15
        ///17:17
        ///18:19
        ///19:22
        ///20:25
        ///21:28
        ///22:31
        ///23:34
        ///24:37
        ///25:40
        ///26:44
        ///27:48
        ///28:53
        ///29:58
        ///30:63
        ///P:5.
        /// </summary>
        internal static string Stamina {
            get {
                return ResourceManager.GetString("Stamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-0.5
        ///00:0
        ///01:0
        ///02:1
        ///03:1
        ///04:2
        ///05:2
        ///06:3
        ///07:3
        ///08:4
        ///09:4
        ///10:5
        ///11:5
        ///12:6
        ///13:6
        ///14:7
        ///15:7
        ///16:8
        ///17:8
        ///18:9
        ///19:9
        ///20:10
        ///21:10
        ///22:11
        ///23:11
        ///24:12
        ///25:12
        ///26:13
        ///27:13
        ///28:14
        ///29:14
        ///30:15
        ///31:15
        ///32:16
        ///33:16
        ///34:17
        ///35:17
        ///36:18
        ///37:18
        ///38:19
        ///39:19
        ///40:20
        ///41:20
        ///42:21
        ///43:21
        ///44:22
        ///45:22
        ///46:23
        ///47:23
        ///48:24
        ///49:24
        ///50:25
        ///P:0.5.
        /// </summary>
        internal static string Standard_EPMP {
            get {
                return ResourceManager.GetString("Standard_EPMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-1
        ///00:20
        ///01:21
        ///02:22
        ///03:23
        ///04:24
        ///05:25
        ///06:26
        ///07:27
        ///08:28
        ///09:29
        ///10:30
        ///11:31
        ///12:32
        ///13:33
        ///14:34
        ///15:35
        ///16:37
        ///17:39
        ///18:41
        ///19:43
        ///20:45
        ///21:47
        ///22:49
        ///23:51
        ///24:53
        ///25:55
        ///26:57
        ///27:59
        ///28:61
        ///29:63
        ///30:65
        ///31:67
        ///32:68
        ///33:71
        ///34:73
        ///35:75
        ///36:78
        ///37:81
        ///38:84
        ///39:87
        ///40:90
        ///41:93
        ///42:96
        ///43:99
        ///44:102
        ///45:105
        ///46:108
        ///47:111
        ///48:114
        ///49:117
        ///50:120
        ///P:5.
        /// </summary>
        internal static string Standard_HP {
            get {
                return ResourceManager.GetString("Standard_HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACC:Accuracy
        ///AGI:Agility
        ///AGIMOD:Agility Modifier
        ///AGIEPB:EP Bonus - AGI
        ///AWA:Awareness
        ///BAL:Balance
        ///BDEF:Base Defense
        ///BDMG:Base Damage
        ///BLURES:Blunt Resistance
        ///CC:Crit. Chance
        ///CHA:Charisma
        ///CHAMOD:Charisma Modifier
        ///CHAEPB:EP Bonus - CHA
        ///CHAMPB:MP Bonus - CHA
        ///CHAN:Channeling
        ///CONC:Concentration
        ///COLRES:Cold Resistance
        ///DARRES:Dark Resistance
        ///DB:Dodge/Block
        ///DDG:Dodge
        ///DEF:Defense
        ///DMG:Damage
        ///DTM:Detect Magic
        ///EP:Energy Points
        ///EPC:EP Channel
        ///EXHA:Exhaustion
        ///FOR:Fortitude
        ///FORRES:Force Resistance [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StatKeywords {
            get {
                return ResourceManager.GetString("StatKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:0
        ///2:0
        ///3:0
        ///4:0
        ///5:1
        ///6:1
        ///7:1
        ///8:1
        ///9:1
        ///10:2
        ///11:2
        ///12:2
        ///13:3
        ///14:4
        ///15:5
        ///16:6
        ///17:8
        ///18:10
        ///19:12
        ///20:15
        ///21:18
        ///22:21
        ///23:24
        ///24:27
        ///25:30
        ///26:34
        ///27:38
        ///28:43
        ///29:48
        ///30:52
        ///P:5.
        /// </summary>
        internal static string Stealth {
            get {
                return ResourceManager.GetString("Stealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:0
        ///-4:0
        ///-3:0
        ///-2:0
        ///-1:0
        ///0:0
        ///1:1
        ///2:1
        ///3:2
        ///4:2
        ///5:3
        ///6:4
        ///7:5
        ///8:6
        ///9:7
        ///10:8
        ///11:10
        ///12:12
        ///13:14
        ///14:16
        ///15:18
        ///16:22
        ///17:26
        ///18:30
        ///19:35
        ///20:40
        ///21:45
        ///22:50
        ///23:55
        ///24:60
        ///25:65
        ///26:75
        ///27:85
        ///28:95
        ///29:105
        ///30:120
        ///P:15.
        /// </summary>
        internal static string Survival {
            get {
                return ResourceManager.GetString("Survival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap switch_arrow {
            get {
                object obj = ResourceManager.GetObject("switch_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap town_mark {
            get {
                object obj = ResourceManager.GetObject("town_mark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1.103 - 12/19/2020
        ///Character Sheet
        ///- Updated Talent/School UI
        ///- Talents and Schools now track progress toward the next rank/level
        ///- Improved Trait/Talent/School/Ability Selection
        ///- Debugged HP Meter interaction
        ///- Minor bug fixes
        ///
        ///
        ///1.1.101 - 12/12/2020
        ///Character Sheet
        ///- Updated UI
        ///- Improved automation
        ///
        ///
        ///1.1.100 - 12/06/2020
        ///- UI Adjustments
        ///Character Sheet
        ///- HP/EP/MP now have visible meters
        ///
        ///
        ///1.1.004 - 11/18/2020
        ///Item Bank
        ///- Improved UI
        ///- Added Magical Effect support
        ///
        ///
        ///1.1.003 - [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string version_history {
            get {
                return ResourceManager.GetString("version_history", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axe
        ///Blade
        ///Bow
        ///Channel
        ///Dagger
        ///Greatblade
        ///Hammer
        ///Knuckles
        ///Magic Glove
        ///Magic Staff
        ///Pistol
        ///Polearm
        ///Rifle
        ///Spear
        ///Staff
        ///Sword
        ///Tome
        ///Wand.
        /// </summary>
        internal static string weapon_types {
            get {
                return ResourceManager.GetString("weapon_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:0
        ///-5:5
        ///-4:10
        ///-3:15
        ///-2:20
        ///-1:25
        ///0:30
        ///1:35
        ///2:40
        ///3:45
        ///4:50
        ///5:55
        ///6:60
        ///7:70
        ///8:80
        ///9:90
        ///10:100
        ///11:120
        ///12:140
        ///13:160
        ///14:180
        ///15:200
        ///16:220
        ///17:240
        ///18:260
        ///19:280
        ///20:300
        ///21:330
        ///22:360
        ///23:390
        ///24:420
        ///25:450
        ///26:500
        ///27:550
        ///28:600
        ///29:650
        ///30:700
        ///P:100.
        /// </summary>
        internal static string WeightAllowance {
            get {
                return ResourceManager.GetString("WeightAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N:-1
        ///-5:-4
        ///-4:-3
        ///-3:-3
        ///-2:-2
        ///-1:-2
        ///0:-2
        ///1:-1
        ///2:-1
        ///3:-1
        ///4:-1
        ///5:0
        ///6:0
        ///7:0
        ///8:0
        ///9:1
        ///10:1
        ///11:1
        ///12:1
        ///13:2
        ///14:2
        ///15:3
        ///16:4
        ///17:5
        ///18:6
        ///19:8
        ///20:10
        ///21:13
        ///22:16
        ///23:19
        ///24:22
        ///25:25
        ///26:28
        ///27:31
        ///28:34
        ///29:37
        ///30:40
        ///P:4.
        /// </summary>
        internal static string Willpower {
            get {
                return ResourceManager.GetString("Willpower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellowBlip {
            get {
                object obj = ResourceManager.GetObject("yellowBlip", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
